import webpush from "web-push";
import { sharedPool } from "./db";

/** Notifications on every device the studio is open on.
 *
 *  He asked for it plainly: every render, every subscriber, every change — on the iMac and on
 *  the phone, wherever the studio is. Web Push does that for free and needs no service, which
 *  matters at a zero budget.
 *
 *  The keys are generated by the server on first use and stored in the database rather than
 *  pasted into an environment variable. Two reasons, and the second is the real one: a VAPID
 *  private key is a secret and must never cross a chat window, and every manual configuration
 *  step in this project has cost hours — the publication id that was never set, the key saved
 *  to the wrong environment, the toggle nobody mentioned. A step that cannot be skipped is a
 *  step that cannot be got wrong. */

const SUBJECT = "mailto:davidpit2008@gmail.com";

async function db() {
  const p = sharedPool();
  if (!p) return null;
  await p.query(`create table if not exists push_keys (
    id int primary key default 1, public text not null, private text not null,
    created_at timestamptz not null default now())`);
  await p.query(`create table if not exists push_subs (
    endpoint text primary key, p256dh text not null, auth text not null,
    label text, created_at timestamptz not null default now(),
    last_ok timestamptz, fails int not null default 0)`);
  // "studio" (default, for every row that predates this column) is the owner's own
  // devices — render/subscriber/connection alerts, all business-internal. "public" is a
  // site visitor who asked to hear about new episodes only. The two must never share a
  // send: a visitor's device receiving a private subscriber-count alert is a real leak,
  // not a cosmetic one.
  await p.query(`alter table push_subs add column if not exists audience text not null default 'studio'`);
  await p.query(`create table if not exists notified_renders (
    episode int primary key, notified_at timestamptz not null default now())`);
  await p.query(`create table if not exists notified_live (
    episode int primary key, notified_at timestamptz not null default now())`);
  return p;
}

async function keys(): Promise<{ public: string; private: string } | null> {
  const p = await db();
  if (!p) return null;
  const r = await p.query<{ public: string; private: string }>(
    "select public, private from push_keys where id = 1",
  );
  if (r.rows[0]) return r.rows[0];
  const k = webpush.generateVAPIDKeys();
  // on conflict: two cold starts can race here, and the first one written must win —
  // a second keypair would silently invalidate every subscription made against the first
  await p.query(
    "insert into push_keys (id, public, private) values (1, $1, $2) on conflict (id) do nothing",
    [k.publicKey, k.privateKey],
  );
  const again = await p.query<{ public: string; private: string }>(
    "select public, private from push_keys where id = 1",
  );
  return again.rows[0] ?? null;
}

/** the browser needs this to subscribe; it is public by design */
export async function publicKey(): Promise<string | null> {
  return (await keys())?.public ?? null;
}

export async function addSub(
  sub: { endpoint: string; keys: { p256dh: string; auth: string } },
  label: string,
  audience: "studio" | "public" = "studio",
): Promise<void> {
  const p = await db();
  if (!p) throw new Error("no database");
  await p.query(
    `insert into push_subs (endpoint, p256dh, auth, label, audience) values ($1,$2,$3,$4,$5)
     on conflict (endpoint) do update set p256dh = $2, auth = $3, label = $4, audience = $5, fails = 0`,
    [sub.endpoint, sub.keys.p256dh, sub.keys.auth, label.slice(0, 80), audience],
  );
}

export async function deviceCount(audience: "studio" | "public" = "studio"): Promise<number> {
  const p = await db();
  if (!p) return 0;
  const r = await p.query<{ n: string }>(
    "select count(*)::text n from push_subs where audience = $1",
    [audience],
  );
  return Number(r.rows[0]?.n ?? 0);
}

export type Note = { title: string; body: string; url?: string; tag?: string };

/** Send to every registered device. Returns what happened, per device, because a
 *  notification that silently failed to arrive is worse than no notification: he would stop
 *  checking the thing he asked to be told about. */
export async function notify(
  n: Note,
  audience: "studio" | "public" = "studio",
): Promise<{ sent: number; gone: number; failed: number }> {
  const p = await db();
  if (!p) return { sent: 0, gone: 0, failed: 0 };
  const k = await keys();
  if (!k) return { sent: 0, gone: 0, failed: 0 };
  webpush.setVapidDetails(SUBJECT, k.public, k.private);

  const subs = await p.query<{ endpoint: string; p256dh: string; auth: string }>(
    "select endpoint, p256dh, auth from push_subs where audience = $1",
    [audience],
  );
  let sent = 0, gone = 0, failed = 0;
  const payload = JSON.stringify(n);

  for (const s of subs.rows) {
    try {
      await webpush.sendNotification(
        { endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } },
        payload,
        { TTL: 3600, urgency: "normal" },
      );
      sent++;
      await p.query("update push_subs set last_ok = now(), fails = 0 where endpoint = $1",
                    [s.endpoint]);
    } catch (e) {
      const code = (e as { statusCode?: number }).statusCode;
      // 404/410 mean the browser threw the subscription away — uninstalled, or permission
      // revoked. Keeping it would make every future send look partly broken.
      if (code === 404 || code === 410) {
        gone++;
        await p.query("delete from push_subs where endpoint = $1", [s.endpoint]);
      } else {
        failed++;
        await p.query("update push_subs set fails = fails + 1 where endpoint = $1",
                      [s.endpoint]);
      }
    }
  }
  return { sent, gone, failed };
}

/** Notify once per episode the first time its render shows up passing the gate — never
 *  again for the same episode, even across re-renders, since "notified_renders" is a
 *  permanent record, not a cache. A render only becomes visible to the live site at
 *  deploy time (the files are static, committed assets, not uploaded), so this is
 *  called from the same place that already checks for other daily changes rather than
 *  needing its own schedule. */
export async function notifyNewRenders(
  passed: { episode: number; title: string | null }[],
): Promise<void> {
  const p = await db();
  if (!p) return;
  for (const r of passed) {
    if (r.episode == null) continue;
    const ins = await p.query(
      "insert into notified_renders (episode) values ($1) on conflict do nothing returning episode",
      [r.episode],
    );
    if (ins.rowCount === 0) continue; // already notified for this episode
    await notify({
      title: `ריל ${r.episode} מוכן`,
      body: r.title ? r.title : `הרנדור עבר את כל הבדיקות.`,
      url: "/renders",
      tag: `render-${r.episode}`,
    }).catch(() => {});
  }
}

/** The visitor-facing counterpart of notifyNewRenders — same once-ever guarantee, its own
 *  table so an episode's "gate passed" (internal) and "went live" (public) never share a
 *  row, and its own audience so a site visitor never sees a studio-facing notification. */
export async function notifyEpisodeLive(episode: number, title: string): Promise<void> {
  const p = await db();
  if (!p) return;
  const ins = await p.query(
    "insert into notified_live (episode) values ($1) on conflict do nothing returning episode",
    [episode],
  );
  if (ins.rowCount === 0) return; // already notified for this episode
  await notify(
    {
      title: "New episode",
      body: title,
      url: `/e/${episode}`,
      tag: `live-${episode}`,
    },
    "public",
  ).catch(() => {});
}
